Delete temp VNC files that can cause bootloop
deconz-community/deconz-docker pull request #104
Opened 2022-04-27 00:00 UTC by MDXDave

See #100

2022-04-27 07:29 UTC, Jo-Be-Co requested changes

2022-04-27 07:29 UTC, Jo-Be-Co commented on docker/root/start.sh
> +# delete VNC temp files, that can cause bootloop (see #100)
Shouldn't this be put into the if-block where vnc is started? I would place it in the area where folders and links are created.
And imho for clearance the option `-f` should be put in front of the paths.

I was wondering why the folder `/tmp/.X11-unix/` is to be kept.

2022-04-27 07:35 UTC, phdelodder commented on docker/root/start.sh
> +# delete VNC temp files, that can cause bootloop (see #100)
@MDXDave Please change it, to only remove the tmp files when VNC is going to be started.

2022-04-27 15:35 UTC, Jo-Be-Co commented
One last addition to the names of the lock files.

If you use a different `DECONZ_VNC_PORT` the VNC will create a different display number and with it also different lock files. I.e. using Port 5909 will lead to the files `/tmp/.X9-lock` and `/tmp/.X11-unix/X9`.

So using wildcards is the right thing to do if you want to delete the files manually.

2022-05-01 07:07 UTC, phdelodder commented
@MDXDave can you please implement the changes that @Jo-Be-Co recommends?

2022-05-02 07:06 UTC, Jo-Be-Co commented
If need I could implement these in my own fork ... but I don't want to hijack this improvement.

2022-05-02 18:43 UTC, senilio commented
> If needed I could implement these in my own fork ... but I don't want to hijack this improvement.

@Jo-Be-Co  Considering we're seeing reports from more and more users that would be helped by implementation, I vote for getting this change out in a separate PR. You can always credit @MDXDave for highlighting the issue and starting the discussion :)

2022-05-03 04:25 UTC, senilio commented
Superseded by https://github.com/deconz-community/deconz-docker/pull/107

2022-05-03 04:25 UTC, closed without merging

2022-05-09 13:01 UTC, patricstar1986 commented
Hello,

I still have the problem with VNC. 
Latest version is installed. 

Deleting the lockfiles X10-lock and /tmp/.X11-unix/X10 does not bring success.
I have set port 5910. 
Also changing to another one does not bring success. 
Does anyone else have a suggestion?
My version is 2.15.03, Synology Docker.

With version 2.14.01 everything works.

Thanks

2022-05-10 01:04 UTC, Jo-Be-Co commented
My `2.15.03` is doing find on DSM7 ... could you show us your startup log?

You also could try to start with `DECONZ_UID=0` and `DECONZ_GID=0`.

2022-05-10 05:27 UTC, patricstar1986 commented
mit uid 0 zund gid 0 habe ich es schon versucht. 

Anbei das Log wenn ich VNC aktiviere. Ohne Vnc funktioniert es. 


[_deconzcommunity_deconz_logs.txt](https://github.com/deconz-community/deconz-docker/files/8657638/_deconzcommunity_deconz_logs.txt)